allowBuilds:
  '@clerk/shared': true
  '@prisma/engines': true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/engines'
  - msgpackr-extract
  - msw
  - prisma
